server:
  port: 0
spring:
  application:
    name: swcamp-user-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/menudb
    username: swcamp
    password: swcamp

  # jpa config
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database: mysql
    properties:
      hibernate:
        format_sql: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

# yml ??? ???? ?? ??
swcamp:
  message: Let's do MSA!

#token:
#  # JWT 토큰의 만료시간 설정(ms단위)
#  expiration_time: 43200000 # 12간으로 설정
#
#  # JWT 토큰의 Verify Signature를 위한 secret-key
#  secret: l1Z5I9WufSD5qM0UTHXDJa1kaGxBlyhKMbx+ONkqzeRTlKdF8Bq37mA3Z8nhjRlwVUrL/u3bdkFeamIrUoWvVw==

# actuator 추가 후
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans