server:
  port: 0

spring:
  application:
    name: swcamp-user-service

  ## db config
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/menudb
    username: swcamp
    password: swcamp

  # jpa config
  jpa:
#    generate-ddl: on
    hibernate:
      ddl-auto: create
    show-sql: true
    database: mysql
    properties:
      hibernate:
        '[format_sql]': true

# eureka.client.fetch-registry=true? eureka ????? ???? ???? ?????
# ??? ?? ? ??? ???? ????.
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

## ?? ??? ?? ? ??
greeting:
  message: Welcome to the Simple E-commerce.

## config 서버 추가 후 주석
#token:
#  expiration_time: 86400000
#  secret: l1Z5I9WufSD5qM0UTHXDJa1kaGxBlyhKMbx+ONkqzeRTlKdF8Bq37mA3Z8nhjRlwVUrL/u3bdkFeamIrUoWvVw==

## actuator 추가 후
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans

